services:
  haproxy:
    image: haproxy:3.0-alpine
    container_name: rinha-haproxy
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "30MB"

  api1:
    image: cleissonb/rinha-backend-2026-nim:0.1.1
    pull_policy: always
    container_name: rinha-api1
    environment:
      - API_PORT=8080
      - VECTORS_PATH=/data/vectors.bin
      - LABELS_PATH=/data/labels.bin
      - IVF_PATH=/data/ivf.bin
      - HTTP_THREADS=2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "160MB"

  api2:
    image: cleissonb/rinha-backend-2026-nim:0.1.1
    pull_policy: always
    container_name: rinha-api2
    environment:
      - API_PORT=8080
      - VECTORS_PATH=/data/vectors.bin
      - LABELS_PATH=/data/labels.bin
      - IVF_PATH=/data/ivf.bin
      - HTTP_THREADS=2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "160MB"

networks:
  rinha:
    driver: bridge
