services:
  lb:
    build:
      context: .
      dockerfile: Dockerfile.lb
    image: cleissonb/rinha-backend-2026-hare-lb:0.1.1
    container_name: rinha-lb
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      rinha:
        ipv4_address: 172.30.0.10
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "30MB"

  api1:
    build: .
    image: cleissonb/rinha-backend-2026-nim:0.1.2
    container_name: rinha-api1
    environment:
      - API_PORT=8080
      - VECTORS_PATH=/data/vectors.bin
      - LABELS_PATH=/data/labels.bin
      - RESIDUALS_PATH=/data/residuals.bin
      - IVF_PATH=/data/ivf.bin
      - HTTP_THREADS=2
    networks:
      rinha:
        ipv4_address: 172.30.0.11
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "160MB"

  api2:
    build: .
    image: cleissonb/rinha-backend-2026-nim:0.1.2
    container_name: rinha-api2
    environment:
      - API_PORT=8080
      - VECTORS_PATH=/data/vectors.bin
      - LABELS_PATH=/data/labels.bin
      - RESIDUALS_PATH=/data/residuals.bin
      - IVF_PATH=/data/ivf.bin
      - HTTP_THREADS=2
    networks:
      rinha:
        ipv4_address: 172.30.0.12
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "160MB"

networks:
  rinha:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
